use crate::catalog::index::ResolvedItem;
use crate::catalog::resolver::Resolver;
use crate::catalog::CatalogSource;

pub fn export(
    name: &str,
    format: &str,
    source: &CatalogSource,
) -> Result<(), Box<dyn std::error::Error>> {
    let resolver = Resolver::load_from(source)?;
    let items = resolver.resolve(name)?;

    let tools: Vec<_> = items
        .iter()
        .filter_map(|item| match item {
            ResolvedItem::Tool(req) => Some(req.name.as_str()),
            ResolvedItem::Pdk(_) => None,
        })
        .collect();

    match format {
        "dockerfile" => {
            println!("# Dockerfile generated by edash export --format dockerfile {}", name);
            println!("FROM ubuntu:22.04");
            println!("RUN apt-get update && apt-get install -y curl");
            println!("COPY --from=edash /usr/local/bin/edash /usr/local/bin/edash");
            println!("COPY edash.lock /project/edash.lock");
            println!("RUN edash install {}", name);
            println!("WORKDIR /project");
        }
        "github-actions" => {
            println!("# GitHub Actions workflow generated by edash export");
            println!("# Save this to .github/workflows/eda-ci.yml");
            println!("name: EDA CI ({})", name);
            println!("on: [push, pull_request]");
            println!("jobs:");
            println!("  eda:");
            println!("    runs-on: ubuntu-latest");
            println!("    steps:");
            println!("      - uses: actions/checkout@v4");
            println!("      - name: Install {} tools", name);
            println!("        run: |");
            for t in &tools {
                println!("          edash install {}", t);
            }
        }
        "offline-bundle" => {
            println!("Offline bundle export not yet implemented.");
            println!("Tools in {}: {}", name, tools.join(", "));
        }
        _ => {
            return Err(format!("Unknown export format: {}. Use dockerfile, github-actions, or offline-bundle", format).into());
        }
    }

    Ok(())
}
